#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - git

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

runcmd:
  - echo "Hello from cloud-init!" > /tmp/cloud-init-test.txt
  - chmod 644 /tmp/cloud-init-test.txt

final_message: "Cloud-init configuration completed successfully!"
