version: '3'

tasks:

  run:
    cmds:
      - go run .

  build:
    cmds:
      - go build -o passgo -ldflags="-s -w"
      - echo "Build complete. Run ./passgo to start the application."
      
  build-all:
    cmds:
      - GOOS=darwin  GOARCH=arm64 go build -o passgo-macos-arm64 -ldflags="-s -w"
      - GOOS=darwin  GOARCH=amd64 go build -o passgo-macos-amd64 -ldflags="-s -w"
      - GOOS=linux   GOARCH=arm64 go build -o passgo-linux-arm64 -ldflags="-s -w"
      - GOOS=linux   GOARCH=amd64 go build -o passgo-linux-amd64 -ldflags="-s -w"
      - GOOS=windows GOARCH=arm64 go build -o passgo-windows-arm64.exe -ldflags="-s -w"
      - GOOS=windows GOARCH=amd64 go build -o passgo-windows-amd64.exe -ldflags="-s -w"

  build-all-upx:
    cmds:
      - GOOS=darwin  GOARCH=arm64 go build -o passgo-macos-arm64 -ldflags="-s -w"
      - GOOS=darwin  GOARCH=amd64 go build -o passgo-macos-amd64 -ldflags="-s -w"
      - GOOS=linux   GOARCH=arm64 go build -o passgo-linux-arm64 -ldflags="-s -w"
      - GOOS=linux   GOARCH=amd64 go build -o passgo-linux-amd64 -ldflags="-s -w"
      - GOOS=windows GOARCH=arm64 go build -o passgo-windows-arm64.exe -ldflags="-s -w"
      - GOOS=windows GOARCH=amd64 go build -o passgo-windows-amd64.exe -ldflags="-s -w"
      - upx passgo-linux-arm64
      - upx passgo-linux-amd64
      - upx passgo-windows-arm64.exe
      - upx passgo-windows-amd64.exe

  delete-builds:
    cmds:
      - rm -f passgo-macos-arm64 passgo-macos-amd64 passgo-linux-arm64 passgo-linux-amd64 passgo-windows-arm64.exe passgo-windows-amd64.exe
      - echo "All builds deleted."

  full-test:
    cmds:
     - multipass delete --all
     - multipass purge
     - multipass launch --name vm1
     - multipass launch --name vm2
     - multipass stop vm1
     - multipass stop vm2
     - multipass delete --all
     - multipass purge
  
  # create-mixed-instances:
  cmi:
    cmds:
     - multipass delete --all
     - multipass purge
     - multipass launch  --name vm1
     - multipass launch  --name vm2
     - multipass launch  --name vm3
     - multipass stop    vm2
     - multipass suspend vm3

  create-test-instances:
    cmds:
     - multipass delete --all
     - multipass purge
     - multipass launch --name vm1
     - multipass launch --name vm2

  stop-all:
    cmds:
     - multipass stop --all

  start-all:
    cmds:
     - multipass start --all

  delete-all:
    cmds:
     - multipass delete --all
     - multipass purge