version: '3'

tasks:

  run:
    cmds:
      - go run .

  build:
    cmds:
      - go build -o gopass
      - echo "Build complete. Run ./gopass to start the application."
      
  build-all:
    cmds:
      - GOOS=darwin  GOARCH=arm64 go build -o gopass-macos-arm64
      - GOOS=darwin  GOARCH=amd64 go build -o gopass-macos-amd64
      - GOOS=linux   GOARCH=arm64 go build -o gopass-linux-arm64
      - GOOS=linux   GOARCH=amd64 go build -o gopass-linux-amd64
      - GOOS=windows GOARCH=arm64 go build -o gopass-windows-arm64.exe
      - GOOS=windows GOARCH=amd64 go build -o gopass-windows-amd64.exe

  delete-builds:
    cmds:
      - rm -f gopass-macos-arm64 gopass-macos-amd64 gopass-linux-arm64 gopass-linux-amd64 gopass-windows-arm64.exe gopass-windows-amd64.exe
      - echo "All builds deleted."